# Generated by Django 4.1 on 2022-09-04 02:57

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'CategoryProduct',
                'verbose_name_plural': 'CategoryProducts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted date')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical CategoryProduct',
                'verbose_name_plural': 'historical CategoryProducts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted date')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Indicator',
                'verbose_name_plural': 'historical Indicator',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted date')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical MeasureUnit',
                'verbose_name_plural': 'historical MeasureUnits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'MeasureUnit',
                'verbose_name_plural': 'MeasureUnits',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product image')),
                ('category_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Category product')),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Measure unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Descount indicator')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicator',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted date')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product description')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Product image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Category product')),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
